In [128]:
import pandas as pd
import numpy as np

In [130]:
df = pd.read_csv('City Council/2019_November Municipal (General) City Council At Large Results.csv')
df = df[df.columns[0:17]]
cvap = pd.read_csv('2015-2019_Precinct_CVAP.csv')
df = df.drop('Unnamed: 0', axis=1)
#df = df.drop('Unnamed: 0.1', axis=1)
#df = df.drop('Unnamed: 0.1.1', axis=1)
df['CVAP'] = np.zeros(len(df))
df['TOTAL POP.'] = np.zeros(len(df))
df['WHITE'] = np.zeros(len(df))
df['AFRICAN_AMERICAN'] = np.zeros(len(df))
df['NATIVE_AMERICAN'] = np.zeros(len(df))
df['ASIAN'] = np.zeros(len(df))
df['OTHER'] = np.zeros(len(df))
df

,Ward/Precinct,MICHAEL F FLAHERTY,ALEJANDRA NICOLE STGUILLEN,MICHELLE WU,JULIA MEJIA,ERIN J MURPHY,ALTHEA GARRISON,DAVID HALBERT,ANNISSA ESSAIBI GEORGE,ALL OTHERS,...,BLANKS,BALLOTS CAST,Registered Voters,CVAP,TOTAL POP.,WHITE,AFRICAN_AMERICAN,NATIVE_AMERICAN,ASIAN,OTHER
0,101,119,92,180,93,51,54,136,163,4,...,228,280,1485,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,102,72,53,86,55,29,19,42,73,0,...,159,147,1108,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,103,174,145,207,167,64,59,104,175,4,...,397,374,2665,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,104,52,57,79,54,22,19,36,66,4,...,111,125,1122,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,105,65,57,78,50,35,18,42,70,1,...,116,133,1376,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2209,111,86,161,62,56,45,45,177,2,...,367,278,1362,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250,2210,146,125,245,98,74,82,50,207,3,...,346,344,1583,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251,2211,152,69,157,64,74,69,28,128,2,...,253,249,1068,0.0,0.0,0.0,0.0,0.0,0.0,0.0
252,2212,155,86,155,69,85,71,38,135,0,...,334,282,1257,0.0,0.0,0.0,0.0,0.0,0.0,0.0
253,2213,114,73,138,54,56,47,38,102,0,...,266,222,948,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
for i in range(len(cvap)):
    wp = cvap.loc[i, 'WARD_PRECI']
    if wp == '0502A':
        wp = '0502'
    filt = df['Ward/Precinct'] == int(wp)
    ind = df.index[filt].tolist()[0]
    df.loc[ind, 'CVAP'] += cvap.loc[i, 'CVAP']

In [93]:
dems = pd.read_csv('Precinct_Demographics_Based_On_2015-19_ACS_Census_Data.csv')
dems = dems.drop('Unnamed: 0', axis=1)

for i in range(len(dems)):
    for c in dems.columns[2:]:
        dems.loc[i, c] = round(dems.loc[i, c]/dems.loc[i, 'TOTAL'], 3)

for i in range(len(dems)):
    wp = cvap.loc[i, 'WARD_PRECI']
    if wp == '0502A':
        wp = '0502'
    filt = df['Ward/Precinct'] == int(wp)
    ind = df.index[filt].tolist()[0]
    df.loc[ind, 'TOTAL POP.'] += dems.loc[i, 'TOTAL']
    df.loc[ind, 'WHITE'] += dems.loc[i, 'WHITE']
    df.loc[ind, 'AFRICAN_AMERICAN'] += dems.loc[i, 'AFRICAN_AMERICAN']
    df.loc[ind, 'NATIVE_AMERICAN'] += dems.loc[i, 'NATIVE_AMERICAN']
    df.loc[ind, 'ASIAN'] += dems.loc[i, 'ASIAN']
    df.loc[ind, 'OTHER'] += dems.loc[i, 'OTHER']

In [94]:
df.to_csv('City Council/2019_November Municipal (General) City Council At Large Results.csv')

In [122]:
df = pd.read_csv('Mayoral Election/2017_November Municipal (General) Mayoral Results.csv')
df = df[df.columns[0:14]]
cvap = pd.read_csv('2015-2019_Precinct_CVAP.csv')
df = df.drop('Unnamed: 0', axis=1)
df = df.drop('Unnamed: 0.1', axis=1)
df = df.drop('Walsh Percentage of votes', axis=1)
df = df.drop('Jackson Percentage of votes', axis=1)
df = df.drop('WP', axis=1)
#df = df.drop('Unnamed: 0.1.1', axis=1)
df['CVAP'] = np.zeros(len(df))
df['TOTAL POP.'] = np.zeros(len(df))
df['WHITE'] = np.zeros(len(df))
df['AFRICAN_AMERICAN'] = np.zeros(len(df))
df['NATIVE_AMERICAN'] = np.zeros(len(df))
df['ASIAN'] = np.zeros(len(df))
df['OTHER'] = np.zeros(len(df))
df = df[:254]
df

,Ward_Precinct,TITO JACKSON,MARTIN J WALSH,DONALD OSGOOD SR (WRITE-IN),ALL OTHERS,VOTES CAST,BLANKS,BALLOTS CAST,Registered Voters,CVAP,TOTAL POP.,WHITE,AFRICAN_AMERICAN,NATIVE_AMERICAN,ASIAN,OTHER
0,101.0,162.0,315.0,0.0,4.0,481.0,14.0,495.0,1397.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,102.0,98.0,189.0,0.0,3.0,290.0,8.0,298.0,1035.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,103.0,233.0,453.0,0.0,6.0,692.0,19.0,711.0,2379.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,104.0,59.0,162.0,0.0,2.0,223.0,7.0,230.0,798.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,105.0,87.0,254.0,0.0,3.0,344.0,11.0,355.0,1255.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2209.0,99.0,177.0,0.0,3.0,279.0,5.0,284.0,1328.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250,2210.0,149.0,237.0,0.0,2.0,388.0,3.0,391.0,1455.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251,2211.0,90.0,168.0,0.0,2.0,260.0,5.0,265.0,1041.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
252,2212.0,84.0,196.0,0.0,2.0,282.0,2.0,284.0,1200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
253,2213.0,77.0,176.0,0.0,1.0,254.0,8.0,262.0,930.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [124]:
for i in range(len(cvap)):
    wp = cvap.loc[i, 'WARD_PRECI']
    if wp == '0502A':
        wp = '0502'
    filt = df['Ward_Precinct'] == int(wp)
    ind = df.index[filt].tolist()[0]
    df.loc[ind, 'CVAP'] += cvap.loc[i, 'CVAP']

In [126]:
dems = pd.read_csv('Precinct_Demographics_Based_On_2015-19_ACS_Census_Data.csv')
dems = dems.drop('Unnamed: 0', axis=1)

for i in range(len(dems)):
    for c in dems.columns[2:]:
        dems.loc[i, c] = round(dems.loc[i, c]/dems.loc[i, 'TOTAL'], 3)

for i in range(len(dems)):
    wp = cvap.loc[i, 'WARD_PRECI']
    if wp == '0502A':
        wp = '0502'
    filt = df['Ward_Precinct'] == int(wp)
    ind = df.index[filt].tolist()[0]
    df.loc[ind, 'TOTAL POP.'] += dems.loc[i, 'TOTAL']
    df.loc[ind, 'WHITE'] += dems.loc[i, 'WHITE']
    df.loc[ind, 'AFRICAN_AMERICAN'] += dems.loc[i, 'AFRICAN_AMERICAN']
    df.loc[ind, 'NATIVE_AMERICAN'] += dems.loc[i, 'NATIVE_AMERICAN']
    df.loc[ind, 'ASIAN'] += dems.loc[i, 'ASIAN']
    df.loc[ind, 'OTHER'] += dems.loc[i, 'OTHER']

In [127]:
df.to_csv('Mayoral Election/2017_November Municipal (General) Mayoral Results.csv')

In [166]:
#Adding Hispanic
df = pd.read_csv('City Council/2009_November Municipal (General) City Council At Large Results.csv')
hispanic = pd.read_csv('Precinct_Hispanic_Population_2006-2011.csv')
df.insert(21, 'HISPANIC', np.zeros(len(df)))
for i in range(len(hispanic)):
    try:
        wp = int(hispanic.loc[i, 'WARD_PRECI'])
    except ValueError:
        wp = 502
    filt = df['Ward/Precinct'] == wp
    index = df.index
    ind = index[filt].tolist()[0]
    df.loc[ind, 'HISPANIC'] += round(hispanic.loc[i, 'Hispanic/Latino']/df.loc[ind, 'TOTAL POP.'], 3)
    

df = df.drop('Unnamed: 0', axis=1)
display(df)
df.to_csv('City Council/2009_November Municipal (General) City Council At Large Results.csv')

,Ward/Precinct,STEPHEN J MURPHY,DOUG BENNETT,FELIX G ARROYO,TITO JACKSON,TOMAS GONZALEZ,JOHN R CONNOLLY,ANDREW P KENNEALLY,AYANNA S PRESSLEY,ALL OTHERS,...,BALLOTS CAST,Registered Voters,CVAP,TOTAL POP.,WHITE,AFRICAN_AMERICAN,NATIVE_AMERICAN,ASIAN,HISPANIC,OTHER
0,101,175,62,116,63,41,188,186,73,5,...,397,1113,534.0,960.039645,0.567,0.033,0.000,0.100,0.403,0.146
1,102,147,52,71,25,43,129,115,41,4,...,273,816,814.0,2041.544654,0.667,0.023,0.001,0.057,0.538,0.026
2,103,242,88,217,93,138,217,195,127,2,...,600,1720,1422.0,3134.463144,0.650,0.062,0.003,0.051,0.465,0.048
3,104,78,44,38,18,11,72,73,25,0,...,183,563,537.0,1721.867952,0.567,0.073,0.003,0.032,0.548,0.062
4,105,116,54,82,23,34,110,157,37,4,...,286,960,980.0,3189.980535,0.645,0.032,0.008,0.001,0.640,0.099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2209,144,46,106,70,30,153,78,111,2,...,304,1392,1190.0,1524.975326,0.875,0.019,0.000,0.098,0.039,0.001
250,2210,276,56,189,72,44,235,125,171,6,...,470,1664,1655.0,2258.588637,0.702,0.057,0.001,0.163,0.133,0.072
251,2211,190,33,118,45,25,163,76,89,2,...,316,1079,1730.0,2101.022294,0.793,0.033,0.003,0.123,0.117,0.041
252,2212,211,46,127,47,37,186,103,91,2,...,372,1100,1604.0,2351.383922,0.617,0.067,0.000,0.184,0.199,0.125
253,2213,170,40,77,41,21,155,93,83,0,...,279,911,958.0,1200.265122,0.841,0.023,0.000,0.133,0.053,0.003

In [175]:
df = pd.read_csv('Mayoral Election/2009_November Municipal (General) Mayoral Results.csv')
hispanic = pd.read_csv('Precinct_Hispanic_Population_2006-2011.csv')
df.insert(16, 'HISPANIC', np.zeros(len(df)))
for i in range(len(hispanic)):
    try:
        wp = int(hispanic.loc[i, 'WARD_PRECI'])
    except ValueError:
        wp = 502
    filt = df['Ward Precinct '] == wp
    index = df.index
    ind = index[filt].tolist()[0]
    df.loc[ind, 'HISPANIC'] += round(hispanic.loc[i, 'Hispanic/Latino']/df.loc[ind, 'TOTAL POP.'], 3)
    

df = df.drop('Unnamed: 0', axis=1)
display(df)
df.to_csv('Mayoral Election/2009_November Municipal (General) Mayoral Results.csv')

,Ward Precinct,THOMAS M MENINO,MICHAEL F FLAHERTY,WILLIAM FEEGBEH (WRITE-IN),ALL OTHERS,VOTES CAST,BLANKS,BALLOTS CAST,Registered Voters,CVAP,TOTAL POP.,WHITE,AFRICAN_AMERICAN,NATIVE_AMERICAN,ASIAN,HISPANIC,OTHER
0,101,200,193,0,0,393,4,397,1113,534.0,960.039645,0.567,0.033,0.000,0.100,0.403,0.146
1,102,166,105,0,2,273,0,273,816,814.0,2041.544654,0.667,0.023,0.001,0.057,0.538,0.026
2,103,365,229,0,0,594,6,600,1720,1422.0,3134.463144,0.650,0.062,0.003,0.051,0.465,0.048
3,104,115,66,0,0,181,2,183,563,537.0,1721.867952,0.567,0.073,0.003,0.032,0.548,0.062
4,105,164,121,0,0,285,1,286,960,980.0,3189.980535,0.645,0.032,0.008,0.001,0.640,0.099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2209,147,155,0,0,302,2,304,1392,1190.0,1524.975326,0.875,0.019,0.000,0.098,0.039,0.001
250,2210,244,220,0,3,467,3,470,1664,1655.0,2258.588637,0.702,0.057,0.001,0.163,0.133,0.072
251,2211,168,142,0,1,311,5,316,1079,1730.0,2101.022294,0.793,0.033,0.003,0.123,0.117,0.041
252,2212,192,171,0,2,365,7,372,1100,1604.0,2351.383922,0.617,0.067,0.000,0.184,0.199,0.125
253,2213,144,134,0,1,279,0,279,911,958.0,1200.265122,0.841,0.023,0.000,0.133,0.053,0.003

In [188]:
#Income
df = pd.read_csv('Income_Metrics_By_Precinct_2015-2019.csv')
df.loc[251, 'WARD_PRECI'] = '0502'
df = df.astype({"WARD_PRECI": int})
df = df.sort_values(by='WARD_PRECI').reset_index(drop=False)
df = df.drop('index', axis=1)
df = df.drop('Unnamed: 0', axis=1)
display(df)
df.to_csv('Income_Metrics_By_Precinct_2015-2019.csv')

     WARD_PRECI  Median Household Income  Per Capita Income
0           101                    93699              52756
1           102                    81150              46397
2           103                    72098              43693
3           104                    70361              41089
4           105                    76775              40514
..          ...                      ...                ...
250        2209                    78010              38142
251        2210                    92347              44440
252        2211                    97798              43252
253        2212                    87962              41217
254        2213                   107462              49722

[255 rows x 3 columns]