In [75]:
import pandas as pd
import numpy as np

In [80]:
app_proj = pd.read_csv('UPDATED_approved_projects_with_demographics.csv')
app_zba = pd.read_csv('Approved_Permits_ZBA - zba_approved_permits.csv')
# parcel id column is titled parcel_id in both

In [81]:
for i in range(len(app_proj['issued_date'])):
    string = app_proj.loc[i, 'issued_date']
    year = string[-8:-6]
    if '/' in year:
        year = string[-7:-5]
    app_proj.loc[i, 'issued_date'] = '20' + year

In [82]:
app_proj['issued_date'].unique()

array(['2016', '2010', '2015', '2011', '2019', '2013', '2014', '2017',
       '2018', '2012', '2020'], dtype=object)

In [85]:
for i in range(len(app_zba['issued_date'])):
    if type(app_zba.loc[i, 'issued_date']) != float:
        string = app_zba.loc[i, 'issued_date']
        year = string[0:4]
        app_zba.loc[i, 'issued_date'] = year

In [87]:
app_zba['issued_date'].unique()

array(['2020', '2021', '2015', '2014', '2016', '2017', '2018', '2019',
       '2013'], dtype=object)

In [84]:
print(app_proj.columns)
print('\n')
print(app_zba.columns)

Index(['Unnamed: 0', 'Unnamed: 0.1', 'permitnumber', 'worktype',
       'permittypedescr', 'description', 'comments', 'applicant',
       'declared_valuation', 'total_fees', 'issued_date', 'expiration_date',
       'status', 'owner', 'occupancytype', 'sq_feet', 'address', 'city',
       'state', 'zip', 'property_id', 'parcel_id', 'Cencus_Tract', 'Zipcode',
       'Neighborhood', 'US Geonames Sub-neigborhood', 'Total Population',
       ' Black', 'Black Proportion', 'White', 'White Proportion',
       'American Indian & Alaska Native',
       'American Indian & Alaska Native Proportion', 'Asian',
       'Asian Proportion', 'Male ', 'Male Proportion', 'Female ',
       'Female Proportion ', 'Lat', 'Long', 'Primary Sub-Neighborhood',
       'Secondary Sub-Neighborhood', 'Teritriary Sub-Neighborhood(s)',
       'T-Stop/Commuter Rail'],
      dtype='object')


Index(['Unnamed: 0', 'permitletter', 'permitnumber', 'worktype',
       'permittypedescr', 'description', 'comments', 'applicant',
       'declared_valuation', 'total_fees', 'issued_date', 'expiration_date',
       'status.x', 'owner', 'occupancytype', 'sq_feet', 'address.x', 'city.x',
       'state', 'zip.x', 'property_id', 'parcel_id', 'lat', 'long',
       'address.y', 'status.y', 'boa_apno', 'appeal_type', 'contact',
       'submitted_date', 'received_date', 'hearing_date', 'ever_deferred',
       'num_deferrals', 'final_decision_date', 'decision', 'closed_date',
       'city.y', 'zip.y', 'ward', 'zoning_district', 'project_description'],
      dtype='object')

In [125]:
adds = pd.DataFrame(columns = ['parcel_id', 'Owner.1', 'Owner.2', 'Address'])
adds['parcel_id'] = app_proj['parcel_id']
adds['Owner.1'] = app_proj['owner']
adds.head()

    parcel_id                            Owner.1 Owner.2 Address
0  1000004000                TREMONT & FAXON LLC     NaN     NaN
1  1000007000                TREMONT & FAXON LLC     NaN     NaN
2  1000009000                TREMONT & FAXON LLC     NaN     NaN
3  2006685001                   BARONE MICHAEL J     NaN     NaN
4  2005770000  110 PARK STREET CONDOMINIUM TRUST     NaN     NaN

In [126]:
pa_21 = pd.read_csv('Property Assesments/property-assessment-fy2021.csv')
pa_21 = pa_21.astype({"PID": str})
pa_21.head()

,PID,CM_ID,GIS_ID,ST_NUM,ST_NAME,UNIT_NUM,CITY,ZIPCODE,BLDG_SEQ,NUM_BLDGS,...,KITCHEN_STYLE2,KITCHEN_STYLE3,HEAT_TYPE,HEAT_FUEL,AC_TYPE,FIRE_PLACE,PlUMBING,NUM_PARKING,PROP_VIEW,CORNER_UNIT
0,100001000,NaN,100001000.0,104 A 104,PUTNAM ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,S - Semi-Modern,W - Ht Water/Steam,NaN,N - None,NaN,NaN,3.0,A - Average,NaN
1,100002000,NaN,100002000.0,197,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,M - Modern,M - Modern,F - Forced Hot Air,NaN,C - Central AC,NaN,NaN,NaN,A - Average,NaN
2,100003000,NaN,100003000.0,199,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,S - Semi-Modern,S - Space Heat,NaN,N - None,NaN,NaN,NaN,A - Average,NaN
3,100004000,NaN,100004000.0,201,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,S - Semi-Modern,W - Ht Water/Steam,NaN,N - None,NaN,NaN,NaN,A - Average,NaN
4,100005000,NaN,100005000.0,203,LEXINGTON ST,NaN,EAST BOSTON,2128,1.0,1.0,...,S - Semi-Modern,NaN,W - Ht Water/Steam,NaN,N - None,NaN,NaN,NaN,A - Average,NaN

In [127]:
for i in range(len(adds)):
    pid = adds.loc[i, 'parcel_id']
    filt = pa_21['PID'] == pid
    temp = pa_21[filt]
    temp = temp.reset_index(drop=False)
    if len(temp) == 0:
        pass
    else:
        adds.loc[i, 'Owner.2'] = temp.loc[0, 'OWNER']
        adds.loc[i, 'Address'] = str(temp.loc[0, 'MAIL_ADDRESS']) + ' ' + str(temp.loc[0, 'MAIL_CITY']) + \
                                 ' ' + str(temp.loc[0, 'MAIL_STATE']) + ' ' + str(temp.loc[0, 'MAIL_ZIPCODE'])
adds.head()

,parcel_id,Owner.1,Owner.2,Address
0,1000004000,TREMONT & FAXON LLC,TREMONT & FAXON LLC,109 CHESTNUT ST #5 BOSTON MA 02108
1,1000007000,TREMONT & FAXON LLC,TREMONT & FAXON LLC,109 CHESTNUT ST #5 BOSTON MA 02108
2,1000009000,TREMONT & FAXON LLC,TREMONT & FAXON LLC,109 CHESTNUT ST #5 BOSTON MA 02108
3,2006685001,BARONE MICHAEL J,BARONE MICHAEL J,61 GRAYFIELD AVE WEST ROXBURY MA 02132
4,2005770000,110 PARK STREET CONDOMINIUM TRUST,110 PARK STREET CONDOMINIUM TRUST,95 FARQUHAR STREET ROSLINDALE MA 02131

In [128]:
adds.to_csv('PID_Owner_Comparison_And_Address.csv')

In [104]:
count = 0
for i in range(len(adds_21)):
    if adds_21.loc[i, 'Owner.1'] == adds_21.loc[i, 'Owner.2']:
        count += 1
    else:
        print(adds_21.loc[i, 'Owner.1'])
        print(adds_21.loc[i, 'Owner.2'])
        print('\n')

ALLSTON  STREET  GROUP  LLC
nan


DEDHAM DEVELOPMENT LLC
nan


THREE 61 WEST FOURTH ST
THREE 61 WEST FOURTH ST


BOWENBOSTON LLC
nan


138  OLD  COLONY   LLC
nan


SAM HALL LLC
nan


SALEM COTTAGE LLC
nan


TWO 32 OLD COLONY LP
nan


199 WEST EIGHTH STREET LLC
nan


BARBAR MALCOM
nan


nan
nan


QUINN PAUL J
nan


BELGRADE CROSSING LLC
nan


nan
nan


CHELSEA DEVELOPMENT
CHELSEA DEVELOPMENT


THIRTY6-40 FISHER AVENUE LLC
nan


3200 WASHINGTON ST LLC
nan


3200 WASHINGTON ST LLC
nan


WHITING AVENUE LLC
nan


ROMAN CATH ARCH BOSTON
nan


ROMAN CATH ARCH BOSTON
nan


TWO 72-274 LAMARTINE STREET
nan


NOTO EAST SEVENTH LLC
nan


ROMAN CATHOLIC ARCH BOSTON
nan


ARBORWAY CORP MASS CORP
nan


ARBORWAY CORP MASS CORP
nan


YIP COLLIN CHUN YIN TS
nan


BARTLETT PLACE LAND INC
nan


POWAHOUSE LLC
nan


POWAHOUSE LLC
nan


0 WALNUT LANE LLC
ROCKY PEAK PROPERTY LLC


HUB DEVELOPMENT LLC
SANTOS DENISIO E


CITY POINT PLACE LLC
nan


37 P STREET LLC
nan


CITY POINT PLACE LLC
nan


RADCLIFFE RUSSELL F ETAL
799 DEVELOPMENT LLC


PLYMOUTH & BROCKTON STATION
nan


RMC FILM CAPITAL LLC  TS
nan


DOYLE ROBERT J
319 ATHENS STREET REAL ESTATE LLC


HEGGERTY ALFRED E       ETAL
nan


PIER FOUR INC
nan


PML WEST BROADWAY REALTY
nan


OREILLY TERENCE F
HUYNH DANNY


DESIGN 55 LLC
4 PAYNE ST LLC


DESIGN 55 LLC
4 PAYNE ST LLC


KEMBLE/HAMPDEN LLC
nan


DEOLIVEIRA JULIO C
23 BROOKS STREET LLC


199 HAVRE STREET LLC
SGIA REESIENTIAL BRIDGE LOAN VENTURE V LP


337 CHELSEA STREET LLC
NE HOME INVESTMENTS INC


LAROSA JOSEPH
632 EAST SECOND STREET LLC


FIVE-35 EAST FIRST ST INC
nan


BASSILL ALLAN
nan


nan
nan


CD 709-711 EAST SECOND
nan


K STREET DEVELOPMENT LLC
nan


K STREET DEVELOPMENT LLC
nan


519  EAST  FIRST STREET  INC
nan


PEARSTOWN  DEVELOPMENT  LLC
nan


PEARSTOWN  DEVELOPMENT  LLC
nan


CAD  BUILDERS  LLC
nan


DOWNING FLORENCE M
nan


FIFTY 6 CORNELL ST LLC
nan


CEDARWOOD DEVELOPMENT LLC
nan


BULFINCH CROSSING PRIMARY
BULFINCH CROSSING PRIMARY CONDOMINIUM TRUST


nan
nan


MAF REALTY COMPANY LLC A MASS LLC
MAVERICK STREET INVESTMENT PARTNERS LLC


24  26  28 BROWNING REALTY  TRUST
24, 26, 28 BROWNING REALTY  TRUST


Vo LLC
VO LLC


CATAMOUNT WESTLAND LLC
nan


THIRTEEN HOWELL ST LLC
nan


PIPEFITTERS ASSOC
nan


ECONOMIC DEVELOPMENT AND
nan


nan
nan


HARVARD RE/ALLSTON INC
nan


HARVARD RE/ALLSTON INC
nan


BERACHA VEHATZKLACHA
70 LEO OWNER LLC


HONIG STEPHEN M TRST
RESIDENCES AT 1550 SOLDIERS FIELD ROAD LIMITED PARTNERSHIP


HONIG STEPHEN M TS
RESIDENCES AT SOLDIER FIELD ROAD CONDOMINIUM LIMITED PARTNERSHIP


THIRTY 7-43 N BEACON ST LLC MASS LLC
37-43 N BEACON STREET LLC


THIRTY 7-43 N BEACON ST LLC MASS LLC
37-43 N BEACON STREET LLC


THIRTY 7-43 N BEACON ST LLC MASS LLC
37-43 N BEACON STREET LLC


55-57 BYRON ST LLC
nan


COLERIDGE ONE TWENTY EIGHT LLC
nan


181 COWPER LLC
COWPER RESIDENCES LLC


TRICHILO JOSEPH
TRICHILO DEVELOPMENT LLC


TRICHILO JOSEPH A
TRICHILO DEVELOPMENT LLC


Authorized Agent
BULGROUP COLORADO LLC


nan
nan


nan
nan


NEWFIELD  STREET  LLC
nan


LAGRANGE OAKS LLC
nan


LAGRANGE MANOR LLC
nan


RAFFOL JOSEPH
nan


nan
nan


ROSS CHARLES R
nan


ROSS CHARLES R
nan


MUSTO MARIO
BOSTON RENAISANCE CHARTER PUBLIC SCHOOL


P & N  OBRIEN REALTY  LLC
nan


PLEIM CHRISTOPHER
CLAFCO BUILDERS CORPORATION


nan
nan


BARBER MALCOLM
nan


nan
nan


CABOT  RESIDENTIAL  INC
nan


CABOT  RESIDENTIAL  INC
nan


110  BOLTON  STREET  LLC
nan


110  BOLTON  STREET  LLC
nan


CITY OF BOSTON
nan


CD ATHENS STREET REALTY TRUST
nan


CD ATHENS STREET REALTY TRUST
nan


SUFFOLETTO ERIC
NOOK HILL CONDOMINIUM TRUST


THREE 11 SUMMER STREET LLC
nan


WEST SECOND AT ATHENS LLC
nan


WEST SECOND AT ATHENS LLC
nan


MULREY FRANCES MARJORIE S TS
75WB LLC


EASTERN AVENUE LLC
WILLIAMSON ERIC


HISTORIC FAIRMOUNT LLC
MORAN MICHAEL B


THIRTY POLK STREET LLC
nan


WRENN JOSEPH M
nan


WRENN JOSEPH
nan


CUNNINGHAM STEPHEN A
nan


ORANGE INVESTMENTS LLC
CHRISTINA BORBA


ORANGE  STREET  LLC
nan


PRADHAN NOORUDDIN S
PRADHAN FAMILY TRUST


NOWOSIADLY MATTHEW D
HARRINGTON JOHN


NOWOSIADLY MATTHEW D
HARRINGTON JOHN


6 WESTMINSTER AVENUE REALTY TRUST
45 SPRING STREET LLC


6 WESTMINSTER AVENUE REALTY TRUST
45 SPRING STREET LLC


nan
nan


CALLAHAN KRISTENE R
FERRITER TRACEY


GREALISH JOSEPH
nan


THIRTY 5 AUGUSTUS AV LLC MASS LLC
NUNEZ ALEX


ADAMS  MARINA   LLC
nan


MAKHOUL CHARBEL C
23  METROPOLITAN  LLC


nan
nan


nan
nan


CRUZ HARVARD LLC
CRUZ HARVARD LLC


HA AMY HEUNG
AME REAL ESTATE LLC


BOSTON HOUSING STABILIZATION  INC
PERRY JOHANNE BARTHELEMY


BOSTON HOUSING STABILIZATION  INC
PERRY JOHANNE BARTHELEMY


DORCHESTER GREAT SPACE LLC
nan


OCALLAGHAN TIMOTHY P TS
nan


COFFEY STREET REALTY TR
nan


CHICKATAWBUT 35 LLC
HAT FACTORY TOWN HOUSES AT 35 CHICKATAWBUT ST. CONDOMINIUM TRUST


OCALLAGHAN TIMOTHY P TS
nan


STAR PROPERTY HOLDINGS LLC
348 CHELSEA STREET LLC


SARATOGA INCORPORATED
SARATOGA EB LLC


WEISS BONNIE J
D & W REALTY TRUST OF 1994


MADISON HOUSING DEVELOPMENT
nan


VU MARIA
15-17-19 SARGENT LLC


VU MARIA
15-17-19 SARGENT LLC


NUNEZ WILFREDO
LECCAT LLC


WHITEACRE PROPERTIES LLC
WOOODWARD PARK LLC


DASILVEIRA VARGAS
nan


DASILVEIRA VARGAS
nan


DASILVEIRA VARGAS
nan


TAYS  REALTY  LLC
nan


BASILE PAOLO    TS
nan


HBLC BUSINESS TRUST
nan


288 MARGINAL STREET LLC
nan


DNI  NORTH  AVENUE  LLC
nan


TABA INC
JOSEPH SHARMA


92 & 94 GEORGE STREET REALTY TRUST
92 GEORGIA REALTY LLC


DAUGHTERS OF ISRAEL  INC.
DAUGHTERS OF ISRAEL, INC.


NICOYA PARTNERS LLC
SANQUINTIN IRIS C


BOSTON REDEVELOPMENT AUTH
nan


BOSTON REDEVELOPMENT AUTH
nan


BOSTON REDEVELOPMENT AUTH
nan


BOSTON REDEVELOPMENT AUTH
nan


BOSTON REDEVELOPMENT AUTH
nan


KENDRICK LLC
nan


CARR PHILIP X JR
CARR FAMILY TRUST


16 OAK STREET LLC
nan


D & B REALTY LLC
nan


334 BUNKER HILL REALTY TRUST
WEBER ARI STERN


MOSS HILL BUILDERS LLC
WANG AUDREY


MOSS HILL BUILDERS LLC
GAROFALO WILLIAM A


nan
nan


SCHETTINO JOHN A
nan


SCHETTINO JOHN A
nan


SCHETTINO JOHN A
nan


SCHETTINO JOHN A
nan


SCHETTINO JOHN A
nan


FIRST ELLINGTON LLC
ELLINGTON NOMINEE TRUST


EGLESTON INFILL LLC
nan


LAROSA JOSEPH TS
nan


LAROSA JOSEPH TS
nan


SEAVIEW LLC
nan


CITY OF BOSTON
nan


POWELL QUEEN
nan


ABDAL-KHALLAQ SHARIF
nan


IANELLA CHRISTOPHER A JR
nan


nan
nan


CAD BUILDERS LLC
nan


ROCLID GLOBAL LLC
nan


TODESCA BROS MASS CORP
nan


VACCA PROPERTY MANAGEMENT  LLC
nan


BG VENTURES LLC
nan


MCDONOUGH MICHAEL J
nan


MCDONOUGH MICHAEL J
nan


BOSTON REDEVELOPMENT AUTH
nan


NEPONSET AVE 24 LLC
DISIPIO DEVELOPMENT LLC


CITY OF BOSTON
nan


DESIMONE CATHERINE G
nan


BOSTON HOUSING AUTHORITY
OLD COLONY PHASE THREE A CONDOMINIUM ASSOCIATION


BOSTON HOUSING AUTHORITY
nan


BOSTON HOUSING AUTHORITY
nan


BOSTON HOUSING AUTHORITY
nan


FORD JOHN J
nan


nan
nan


nan
nan


BOSTON HOUSING AUTHORITY
OLD COLONY PHASE THREE A CONDOMINIUM ASSOCIATION


BOSTON HOUSING AUTHORITY
OLD COLONY PHASE THREE A CONDOMINIUM ASSOCIATION


THIRTEEN 25 FE BOYLSTON LLC
nan


nan
nan


nan
nan


37- 45  BABSONST  LLC
nan


Vo LLC
VO LLC


A&R WASHINGTON ST LLC MASS LLC
223 WASHINGTON ST LLC


CHIN JIM
SCOTT JESSICA


HOBIN GAIL M
nan


BOSTON GARDEN DEVELOPMENT
nan


BOSTON CITY LLC
nan


PEREZ RUBEN D SOTO
SOTO-PEREZ RUBEN D SR


GEORGE DOUGLAS R
332 TALBOT AVENUE LLC


VU  REALTY  LLC
nan


VU  REALTY  LLC
nan


243 CONDOR STREET LLC
MT 243 CONDOR STREET LLC


213 EAST EAGLE LLC
nan


IACOZZA CHRISTOPHER G
15 SWIFT TERRACE CONDOMINIUM TRUST


197-199 CONDOR LLC
VALERINA CONDOR LLC


ACONE RYAN P
224 PRINCETON STREET LLC


TRINITY STUART LLC MASS LLC
TRINITY STUART DEVELOPMENT LLC


97 CONDOR STREET LLC
97 CONDOR STREET EAS LLC


BOSTON HOUSING AUTHORITY
nan


BOSTON HOUSING AUTHORITY
nan


BOSTON REDEVELOPMENT AUTH
nan


MATTAPAN HEALTH CTR RLTY INC
nan


LIRIANO & SONS LLC
BOSTON REAL ESTATE DEVELOPMENT LLC


6-8 ARROW STREET CONDO TRUST
nan


6-8 ARROW STREET CONDO TRUST
nan


TREMONT & BURNEY LLC
9-11 BURNEY LLC


nan
nan


nan
nan


SERT LOT 13  LLC
SERT LOT 13, LLC


ECONOMIC DEVELOPMENT AND
nan


TRIBECA NEWBURY ST OWNER LLC
nan


nan
nan


EAST CONCORD MEDICAL
EAST CONCORD MEDICAL


WJG REALTY COMPANY LLC
nan


nan
nan


BOWENBOSTON LLC
nan


BELGRADE CROSSING LLC
nan


GOLDMINZ AMY K
GOLDMINZ AMY K


THIRTY6-40 FISHER AVENUE LLC
nan


ROMAN CATH ARCH BOSTON
nan


ROMAN CATH ARCH BOSTON
nan


ROMAN CATH ARCH BOSTON
nan


LAROSA DEVELOPMENT CORP
nan


YIP COLLIN CHUN YIN TS
nan


BREMEN GOVE DEVELOPMENT II LLC
SHARPE AIRPORT BREMEN LLC


BREMEN GOVE DEVELOPMENT II LLC
SHARPE AIRPORT BREMEN LLC


BREMEN GOVE DEVELOPMENT II
nan


PR REALTY LLC
nan


FIFTY 6 CORNELL ST LLC
nan

In [105]:
count += 7
print(count/len(adds_21))

0.7642201834862385

In [108]:
count = 0
for i in range(len(adds_21)):
    if type(adds_21.loc[i, 'Owner.2']) == float and type(adds_21.loc[i, 'Address']) == float:
        count += 1

print(count/len(adds_21))

0.16422018348623854

In [115]:
pa_20 = pd.read_csv('Property Assesments/property-assessment-fy2020.csv')
pa_20 = pa_20.astype({"PID": str})
pa_20.columns

/Users/yagevlevi/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (6,15,27,28,29,34,35,36,37,38,39,40,41,42,44,45,46,47,48,58,59,64,65,66,67,68,69,70,72,73,74) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Index(['PID', 'CM_ID', 'GIS_ID', 'ST_NUM', 'ST_NAME', 'ST_NAME_SUF',
       'UNIT_NUM', 'ZIPCODE', 'PTYPE', 'LU', 'OWN_OCC', 'OWNER',
       'MAIL_ADDRESSEE', 'MAIL_ADDRESS', 'MAIL CS', 'MAIL_ZIPCODE', 'AV_LAND',
       'AV_BLDG', 'AV_TOTAL', 'GROSS_TAX', 'LAND_SF', 'YR_BUILT', 'YR_REMOD',
       'GROSS_AREA', 'LIVING_AREA', 'NUM_FLOORS', 'STRUCTURE_CLASS',
       'R_BLDG_STYL', 'R_ROOF_TYP', 'R_EXT_FIN', 'R_TOTAL_RMS', 'R_BDRMS',
       'R_FULL_BTH', 'R_HALF_BTH', 'R_BTH_STYLE', 'R_BTH_STYLE2',
       'R_BTH_STYLE3', 'R_KITCH', 'R_KITCH_STYLE', 'R_KITCH_STYLE2',
       'R_KITCH_STYLE3', 'R_HEAT_TYP', 'R_AC', 'R_FPLACE', 'R_EXT_CND',
       'R_OVRALL_CND', 'R_INT_CND', 'R_INT_FIN', 'R_VIEW', 'S_NUM_BLDG',
       'S_BLDG_STYL', 'S_UNIT_RES', 'S_UNIT_COM', 'S_UNIT_RC', 'S_EXT_FIN',
       'S_EXT_CND', 'U_BASE_FLOOR', 'U_NUM_PARK', 'U_CORNER', 'U_ORIENT',
       'U_TOT_RMS', 'U_BDRMS', 'U_FULL_BTH', 'U_HALF_BTH', 'U_BTH_STYLE',
       'U_BTH_STYLE2', 'U_BTH_STYLE3', 'U_KITCH_TYPE', 'U_KITCH_STYLE',
       'U_HEAT_TYP', 'U_AC', 'U_FPLACE', 'U_INT_FIN', 'U_INT_CND', 'U_VIEW'],
      dtype='object')

In [117]:
for i in range(len(adds_21)):
    if type(adds_21.loc[i, 'Owner.2']) == float and type(adds_21.loc[i, 'Address']) == float:
        pid = adds_21.loc[i, 'parcel_id']
        filt = pa_20['PID'] == pid
        temp = pa_20[filt]
        temp = temp.reset_index(drop=False)
        if len(temp) == 0:
            pass
        else:
            adds_21.loc[i, 'Owner.2'] = temp.loc[0, 'OWNER']
            adds_21.loc[i, 'Address'] = str(temp.loc[0, 'MAIL_ADDRESS']) + str(temp.loc[0, 'MAIL CS']) + \
                                        str(temp.loc[0, 'MAIL_ZIPCODE'])

In [118]:
count = 0
for i in range(len(adds_21)):
    if type(adds_21.loc[i, 'Owner.2']) == float and type(adds_21.loc[i, 'Address']) == float:
        count += 1

print(count/len(adds_21))

0.16055045871559634