In [88]:
import censusdata
import pandas as pd
import numpy as np
import warnings; warnings.simplefilter('ignore')
import geopandas as gpd

In [133]:
#censusdata.search('acs5', 2015, 'concept', 'age')

In [90]:
#censusdata.printtable(censusdata.censustable('acs5', 2015, 'B01001A'))

In [91]:
df = censusdata.download('acs5', 2015, censusdata.censusgeo([('state', '25'), ('county', '025'), ('tract', '*')]),
                             ['B01001A_001E', 'B01001A_002E', 'B01001A_007E', 'B01001A_008E', 'B01001A_009E', 'B01001A_010E',
                              'B01001A_011E','B01001A_012E', 'B01001A_013E', 'B01001A_014E', 'B01001A_015E', 'B01001A_016E', 
                              'B01001A_017E','B01001A_022E', 'B01001A_023E', 'B01001A_024E', 'B01001A_025E', 'B01001A_026E', 
                              'B01001A_027E','B01001A_028E', 'B01001A_029E', 'B01001A_030E', 'B01001A_031E'])
df = df.reset_index(drop=False)
df.rename(columns = {'index' : 'TRACT', 'B01001A_001E' : 'Total', 'B01001A_002E' : 'Male', 'B01001A_007E' : 'M 18-19', 'B01001A_008E' : 'M 20-24', 
                             'B01001A_009E' : 'M 25-29', 'B01001A_010E' : 'M 30-34','B01001A_011E' : 'M 35-44','B01001A_012E' : 'M 45-54', 
                             'B01001A_013E' : 'M 55-64', 'B01001A_014E' : 'M 65-74', 'B01001A_015E' : 'M 75-84', 
                             'B01001A_016E' : 'M 85+', 'B01001A_017E' : 'Female', 'B01001A_022E' : 'F 18-19', 'B01001A_023E' : 'F 20-24', 
                             'B01001A_024E' : 'F 25-29', 'B01001A_025E' : 'F 30-34', 'B01001A_026E' : 'F 35-44', 'B01001A_027E' : 'F 45-54',
                             'B01001A_028E' : 'F 55-64', 'B01001A_029E' : 'F 65-74', 'B01001A_030E' : 'F 75-84', 'B01001A_031E' : 'F 85+'}, 
                              inplace = True)
for x in range(len(df)):
    df.loc[x, 'TRACT'] = df['TRACT'].unique()[x].geo[2][1]
    
df = df.astype({"TRACT": int})

df

,TRACT,Total,Male,M 18-19,M 20-24,M 25-29,M 30-34,M 35-44,M 45-54,M 55-64,...,F 18-19,F 20-24,F 25-29,F 30-34,F 35-44,F 45-54,F 55-64,F 65-74,F 75-84,F 85+
0,20303,2357,1410,0,94,187,114,433,130,177,...,12,86,141,116,157,48,120,91,48,27
1,40401,2024,727,22,12,101,132,107,77,61,...,7,59,139,189,54,260,127,108,42,92
2,40801,2149,965,19,43,111,325,138,34,176,...,0,55,110,189,228,132,281,97,15,12
3,50101,3111,1597,0,89,142,199,238,186,77,...,23,137,213,149,265,126,103,129,60,6
4,50901,2609,1542,23,131,115,278,295,236,165,...,7,144,95,125,151,134,107,29,53,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,101101,253,124,0,12,0,16,31,43,0,...,0,11,18,15,29,13,11,0,0,0
200,130300,4132,1952,38,55,69,188,276,379,285,...,19,44,53,205,204,402,345,187,124,100
201,140102,2035,879,0,53,113,45,94,114,140,...,16,35,99,51,184,130,209,154,82,26
202,140300,1464,690,12,81,70,83,29,93,96,...,16,58,42,97,100,122,87,77,19,50
203,180400,1820,812,28,77,20,47,98,134,89,...,16,51,102,43,107,216,124,87,72,19

In [92]:
template = pd.read_csv('Precinct_Make_Up_Of_Census_Tracts.csv')
template = template.drop('Unnamed: 0', axis=1)

prct_age = pd.DataFrame(0, index=np.arange(len(template.columns[2:])),
                        columns=df.columns[1:])

prct_age.insert(0, 'WARD_PRECI', template.columns[2:])

for i in range(len(prct_age)):
    prct = prct_age['WARD_PRECI'].loc[i]
    temp = template[['TRACT', prct]]
    for n in range(len(temp)):
        if temp[prct].loc[n] != 0:
            dec = temp.loc[n, prct]
            filt = df['TRACT'] == temp.loc[n, 'TRACT']
            for c in df.columns[1:]:
                prct_age[c].iloc[i] += round(df[filt][c] * dec)

In [93]:
prct_age

,WARD_PRECI,Total,Male,M 18-19,M 20-24,M 25-29,M 30-34,M 35-44,M 45-54,M 55-64,...,F 18-19,F 20-24,F 25-29,F 30-34,F 35-44,F 45-54,F 55-64,F 65-74,F 75-84,F 85+
0,0102,2056.0,1141.0,19.0,95.0,170.0,171.0,191.0,131.0,43.0,...,7.0,50.0,121.0,80.0,143.0,117.0,38.0,40.0,74.0,14.0
1,0105,1961.0,1128.0,17.0,82.0,193.0,161.0,194.0,158.0,25.0,...,5.0,22.0,66.0,94.0,157.0,123.0,53.0,37.0,38.0,17.0
2,0203,1174.0,534.0,0.0,12.0,69.0,63.0,115.0,53.0,57.0,...,2.0,12.0,92.0,121.0,110.0,60.0,69.0,31.0,38.0,8.0
3,0205,1217.0,583.0,0.0,16.0,90.0,89.0,139.0,47.0,49.0,...,0.0,14.0,83.0,114.0,129.0,70.0,71.0,34.0,19.0,3.0
4,0204,1300.0,622.0,0.0,20.0,88.0,88.0,142.0,55.0,55.0,...,3.0,14.0,87.0,116.0,138.0,80.0,75.0,38.0,19.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,1818,1114.0,524.0,12.0,43.0,40.0,39.0,52.0,70.0,86.0,...,11.0,33.0,27.0,49.0,77.0,100.0,88.0,64.0,30.0,28.0
250,0502A,1065.0,506.0,54.0,89.0,114.0,82.0,67.0,43.0,11.0,...,22.0,208.0,156.0,57.0,32.0,12.0,23.0,11.0,4.0,8.0
251,0115,30.0,13.0,0.0,0.0,1.0,0.0,0.0,2.0,8.0,...,1.0,3.0,1.0,3.0,3.0,0.0,2.0,0.0,5.0,0.0
252,0104,1284.0,715.0,8.0,73.0,91.0,81.0,115.0,143.0,34.0,...,8.0,23.0,104.0,30.0,151.0,78.0,22.0,25.0,18.0,8.0
253,2002,1942.0,912.0,5.0,12.0,102.0,103.0,132.0,150.0,101.0,...,10.0,23.0,119.0,111.0,183.0,134.0,135.0,79.0,38.0,26.0

In [94]:
'0113' in prct_age['WARD_PRECI'].unique()

False

In [95]:
prct_age.to_csv('Precinct_Age_Distribution_Based_On_2011-15_ACS_Census_Data.csv')

In [128]:
neighborhoods = gpd.read_file('Boston_Neighborhoods.shp')

props = pd.read_csv('Neighborhood_Make_Up_Of_Precincts.csv')

neigh_age_11_15 = pd.DataFrame(0, index=np.arange(len(neighborhoods['Name'])),
                        columns=prct_age.columns[1:])
neigh_age_11_15.insert(0, 'NEIGHBORHOOD', neighborhoods['Name'])

for i in range(len(neigh_age_11_15)):
    neighb = neigh_age_11_15['NEIGHBORHOOD'].loc[i]
    temp = props[['WARD_PRECI', neighb]]
    for n in range(len(temp)):
        if temp[neighb].loc[n] != 0:
            dec = temp[neighb].loc[n]
            filt = prct_age['WARD_PRECI'] == temp['WARD_PRECI'].loc[n]
            for c in prct_age.columns[1:]:
                try:
                    neigh_age_11_15[c].iloc[i] += round(prct_age[filt][c] * dec)
                except ValueError as v:
                    break

for c in neigh_age_11_15.columns:
    if c != 'NEIGHBORHOOD':
        neigh_age_11_15[c] = neigh_age_11_15[c].round().astype(int)
        
sum_column = neigh_age_11_15['F 55-64'] + neigh_age_11_15['F 65-74'] + neigh_age_11_15['F 75-84'] + neigh_age_11_15['F 85+']
neigh_age_11_15.insert(23, 'F 55+', sum_column)

sum_column = neigh_age_11_15['M 55-64'] + neigh_age_11_15['M 65-74'] + neigh_age_11_15['M 75-84'] + neigh_age_11_15['M 85+']
neigh_age_11_15.insert(12, 'M 55+', sum_column)

sum_column = neigh_age_11_15['F 55+'] + neigh_age_11_15['M 55+']
neigh_age_11_15['Total 55+'] = sum_column

sum_column = neigh_age_11_15['F 18-19'] + neigh_age_11_15['F 20-24'] + neigh_age_11_15['F 25-29'] + \
             neigh_age_11_15['M 18-19'] + neigh_age_11_15['M 20-24'] + neigh_age_11_15['M 25-29']
neigh_age_11_15['Total 18-29'] = sum_column


cols = list(neigh_age_11_15.columns)[2:]

for c in cols:
    for i in range(len(neigh_age_11_15)):
        neigh_age_11_15.loc[i, c] = round(neigh_age_11_15.loc[i, c]/neigh_age_11_15.loc[i, 'Total'], 3)

neigh_age_11_15

,NEIGHBORHOOD,Total,Male,M 18-19,M 20-24,M 25-29,M 30-34,M 35-44,M 45-54,M 55-64,...,F 30-34,F 35-44,F 45-54,F 55-64,F 65-74,F 75-84,F 55+,F 85+,Total 55+,Total 18-29
0,Roslindale,17565,0.469,0.004,0.012,0.043,0.043,0.073,0.076,0.065,...,0.044,0.097,0.075,0.082,0.033,0.026,0.158,0.018,0.284,0.129
1,Jamaica Plain,25615,0.477,0.005,0.042,0.072,0.060,0.075,0.067,0.047,...,0.072,0.073,0.056,0.055,0.033,0.015,0.119,0.015,0.211,0.253
2,Mission Hill,7548,0.540,0.063,0.213,0.076,0.029,0.039,0.028,0.031,...,0.029,0.026,0.027,0.014,0.022,0.012,0.065,0.018,0.135,0.639
3,Longwood,4006,0.387,0.134,0.153,0.039,0.007,0.017,0.011,0.005,...,0.021,0.013,0.006,0.009,0.010,0.008,0.038,0.011,0.055,0.854
4,Bay Village,859,0.496,0.027,0.029,0.066,0.094,0.066,0.027,0.057,...,0.071,0.069,0.045,0.045,0.036,0.017,0.102,0.003,0.239,0.303
5,Leather District,239,0.464,0.084,0.063,0.067,0.054,0.042,0.054,0.038,...,0.046,0.042,0.038,0.021,0.025,0.008,0.054,0.000,0.130,0.540
6,Chinatown,1258,0.469,0.076,0.056,0.067,0.059,0.046,0.052,0.039,...,0.049,0.045,0.038,0.025,0.028,0.009,0.063,0.002,0.145,0.508
7,North End,6417,0.510,0.001,0.062,0.142,0.076,0.061,0.051,0.030,...,0.066,0.052,0.025,0.032,0.035,0.025,0.106,0.013,0.204,0.423
8,Roxbury,10398,0.562,0.063,0.138,0.055,0.052,0.057,0.038,0.049,...,0.038,0.063,0.045,0.031,0.013,0.008,0.055,0.003,0.135,0.428
9,South End,14672,0.547,0.007,0.043,0.075,0.088,0.082,0.083,0.064,...,0.084,0.065,0.053,0.037,0.029,0.010,0.076,0.001,0.188,0.252
10,Back Bay,16291,0.471,0.036,0.051,0.083,0.057,0.056,0.044,0.056,...,0.077,0.042,0.040,0.062,0.049,0.022,0.144,0.010,0.259,0.367
11,East Boston,20398,0.533,0.009,0.041,0.065,0.071,0.093,0.068,0.043,...,0.045,0.076,0.058,0.039,0.028,0.019,0.099,0.013,0.188,0.203
12,Charlestown,11106,0.455,0.003,0.013,0.062,0.077,0.093,0.040,0.046,...,0.096,0.080,0.068,0.067,0.036,0.020,0.135,0.012,0.221,0.171
13,West End,4265,0.532,0.005,0.068,0.104,0.058,0.095,0.056,0.046,...,0.068,0.047,0.025,0.045,0.034,0.024,0.118,0.014,0.230,0.358
14,Beacon Hill,7675,0.483,0.001,0.030,0.128,0.078,0.056,0.045,0.029,...,0.060,0.051,0.050,0.044,0.046,0.010,0.106,0.006,0.196,0.355
15,Downtown,8282,0.508,0.028,0.051,0.091,0.068,0.053,0.058,0.053,...,0.058,0.051,0.037,0.041,0.041,0.017,0.106,0.008,0.232,0.379
16,Fenway,21046,0.473,0.118,0.144,0.065,0.035,0.034,0.021,0.021,...,0.035,0.020,0.011,0.017,0.010,0.010,0.039,0.003,0.082,0.741
17,Brighton,31632,0.453,0.013,0.099,0.116,0.049,0.039,0.027,0.030,...,0.044,0.036,0.032,0.045,0.032,0.027,0.121,0.017,0.199,0.512
18,West Roxbury,25554,0.458,0.006,0.021,0.030,0.034,0.072,0.068,0.067,...,0.034,0.071,0.088,0.078,0.048,0.038,0.198,0.034,0.341,0.100
19,Hyde Park,11770,0.473,0.008,0.032,0.036,0.035,0.054,0.068,0.071,...,0.031,0.074,0.087,0.078,0.061,0.032,0.189,0.017,0.342,0.145
20,Mattapan,2540,0.493,0.002,0.026,0.022,0.031,0.053,0.083,0.063,...,0.041,0.093,0.078,0.077,0.031,0.020,0.139,0.011,0.254,0.117
21,Dorchester,30225,0.527,0.007,0.037,0.064,0.060,0.074,0.078,0.067,...,0.058,0.070,0.054,0.058,0.030,0.023,0.126,0.015,0.244,0.196
22,South Boston Waterfront,3976,0.513,0.006,0.045,0.139,0.088,0.077,0.054,0.045,...,0.074,0.064,0.055,0.048,0.027,0.016,0.100,0.009,0.177,0.353
23,South Boston,27758,0.498,0.003,0.026,0.137,0.070,0.066,0.054,0.046,...,0.062,0.059,0.047,0.046,0.024,0.022,0.104,0.012,0.189,0.348
24,Allston,16274,0.471,0.059,0.129,0.127,0.045,0.040,0.017,0.022,...,0.035,0.016,0.014,0.020,0.014,0.016,0.052,0.003,0.093,0.706
25,Harbor Islands,30,0.433,0.000,0.000,0.033,0.000,0.000,0.067,0.267,...,0.100,0.100,0.000,0.067,0.000,0.167,0.233,0.000,0.533,0.200

In [129]:
neigh_age_11_15.to_csv('Boston_Neighborhood_Estimated_Age_Distribution_ACS_2011-2015.csv')

In [98]:
df2 = censusdata.download('acs5', 2019, censusdata.censusgeo([('state', '25'), ('county', '025'), ('tract', '*')]),
                             ['B01001A_001E', 'B01001A_002E', 'B01001A_007E', 'B01001A_008E', 'B01001A_009E', 'B01001A_010E',
                              'B01001A_011E','B01001A_012E', 'B01001A_013E', 'B01001A_014E', 'B01001A_015E', 'B01001A_016E', 
                              'B01001A_017E','B01001A_022E', 'B01001A_023E', 'B01001A_024E', 'B01001A_025E', 'B01001A_026E', 
                              'B01001A_027E','B01001A_028E', 'B01001A_029E', 'B01001A_030E', 'B01001A_031E'])
df2 = df2.reset_index(drop=False)
df2.rename(columns = {'index' : 'TRACT', 'B01001A_001E' : 'Total', 'B01001A_002E' : 'Male', 'B01001A_007E' : 'M 18-19', 'B01001A_008E' : 'M 20-24', 
                             'B01001A_009E' : 'M 25-29', 'B01001A_010E' : 'M 30-34','B01001A_011E' : 'M 35-44','B01001A_012E' : 'M 45-54', 
                             'B01001A_013E' : 'M 55-64', 'B01001A_014E' : 'M 65-74', 'B01001A_015E' : 'M 75-84', 
                             'B01001A_016E' : 'M 85+', 'B01001A_017E' : 'Female', 'B01001A_022E' : 'F 18-19', 'B01001A_023E' : 'F 20-24', 
                             'B01001A_024E' : 'F 25-29', 'B01001A_025E' : 'F 30-34', 'B01001A_026E' : 'F 35-44', 'B01001A_027E' : 'F 45-54',
                             'B01001A_028E' : 'F 55-64', 'B01001A_029E' : 'F 65-74', 'B01001A_030E' : 'F 75-84', 'B01001A_031E' : 'F 85+'}, 
                              inplace = True)
for x in range(len(df2)):
    df2.loc[x, 'TRACT'] = df2['TRACT'].unique()[x].geo[2][1]
    
df2 = df2.astype({"TRACT": int})

df2

,TRACT,Total,Male,M 18-19,M 20-24,M 25-29,M 30-34,M 35-44,M 45-54,M 55-64,...,F 18-19,F 20-24,F 25-29,F 30-34,F 35-44,F 45-54,F 55-64,F 65-74,F 75-84,F 85+
0,802,3897,2219,91,521,601,325,276,148,108,...,73,384,417,139,96,141,145,102,22,0
1,10600,2176,1017,0,20,139,186,167,140,156,...,27,64,171,173,129,83,155,232,60,65
2,40100,2369,1071,9,9,135,166,178,104,87,...,0,10,61,243,122,195,222,130,188,10
3,40300,3942,1830,0,19,237,357,334,232,101,...,21,35,234,363,340,238,171,181,25,9
4,50400,1765,1019,14,52,113,176,147,216,94,...,10,14,142,114,119,77,44,83,28,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,82100,720,303,0,0,49,30,2,0,2,...,0,15,31,2,104,74,47,22,0,73
200,60200,2071,987,0,45,262,183,140,90,93,...,0,57,279,197,91,79,116,92,58,0
201,90400,297,153,0,0,72,10,0,25,24,...,0,10,11,11,16,15,0,56,10,2
202,120500,1556,795,0,63,214,157,72,71,62,...,0,46,210,199,98,46,74,29,0,17
203,101001,282,155,0,17,0,0,87,0,0,...,0,0,0,0,39,49,0,22,0,0

In [99]:
prct_age2 = pd.DataFrame(0, index=np.arange(len(template.columns[2:])),
                        columns=df2.columns[1:])

prct_age2.insert(0, 'WARD_PRECI', template.columns[2:])

for i in range(len(prct_age2)):
    prct = prct_age2['WARD_PRECI'].loc[i]
    temp = template[['TRACT', prct]]
    for n in range(len(temp)):
        if temp[prct].loc[n] != 0:
            dec = temp.loc[n, prct]
            filt = df2['TRACT'] == temp.loc[n, 'TRACT']
            for c in df2.columns[1:]:
                prct_age2[c].iloc[i] += round(df2[filt][c] * dec)

In [100]:
prct_age2.to_csv('Precinct_Age_Distribution_Based_On_2015-19_ACS_Census_Data.csv')

In [130]:
neigh_age_15_19 = pd.DataFrame(0, index=np.arange(len(neighborhoods['Name'])),
                        columns=prct_age2.columns[1:])
neigh_age_15_19.insert(0, 'NEIGHBORHOOD', neighborhoods['Name'])

for i in range(len(neigh_age_15_19)):
    neighb = neigh_age_15_19['NEIGHBORHOOD'].loc[i]
    temp = props[['WARD_PRECI', neighb]]
    for n in range(len(temp)):
        if temp[neighb].loc[n] != 0:
            dec = temp[neighb].loc[n]
            filt = prct_age2['WARD_PRECI'] == temp['WARD_PRECI'].loc[n]
            for c in prct_age2.columns[1:]:
                try:
                    neigh_age_15_19[c].iloc[i] += round(prct_age2[filt][c] * dec)
                except ValueError as v:
                    break

for c in neigh_age_15_19.columns:
    if c != 'NEIGHBORHOOD':
        neigh_age_15_19[c] = neigh_age_15_19[c].round().astype(int)
        
sum_column = neigh_age_15_19['F 55-64'] + neigh_age_15_19['F 65-74'] + neigh_age_15_19['F 75-84'] + neigh_age_15_19['F 85+']
neigh_age_15_19.insert(23, 'F 55+', sum_column)

sum_column = neigh_age_15_19['M 55-64'] + neigh_age_15_19['M 65-74'] + neigh_age_15_19['M 75-84'] + neigh_age_15_19['M 85+']
neigh_age_15_19.insert(12, 'M 55+', sum_column)

sum_column = neigh_age_15_19['F 55+'] + neigh_age_15_19['M 55+']
neigh_age_15_19['Total 55+'] = sum_column

sum_column = neigh_age_15_19['F 18-19'] + neigh_age_15_19['F 20-24'] + neigh_age_15_19['F 25-29'] + \
             neigh_age_15_19['M 18-19'] + neigh_age_15_19['M 20-24'] + neigh_age_15_19['M 25-29']
neigh_age_15_19['Total 18-29'] = sum_column

cols = list(neigh_age_15_19.columns)[2:]

for c in cols:
    for i in range(len(neigh_age_15_19)):
        neigh_age_15_19.loc[i, c] = round(neigh_age_15_19.loc[i, c]/neigh_age_15_19.loc[i, 'Total'], 3)
        


neigh_age_15_19

,NEIGHBORHOOD,Total,Male,M 18-19,M 20-24,M 25-29,M 30-34,M 35-44,M 45-54,M 55-64,...,F 30-34,F 35-44,F 45-54,F 55-64,F 65-74,F 75-84,F 55+,F 85+,Total 55+,Total 18-29
0,Roslindale,18466,0.477,0.004,0.017,0.044,0.040,0.083,0.068,0.066,...,0.054,0.084,0.062,0.077,0.044,0.032,0.170,0.017,0.305,0.127
1,Jamaica Plain,27127,0.464,0.004,0.026,0.061,0.071,0.078,0.060,0.054,...,0.074,0.076,0.047,0.071,0.047,0.015,0.150,0.016,0.256,0.212
2,Mission Hill,7275,0.524,0.067,0.223,0.062,0.039,0.024,0.024,0.027,...,0.031,0.025,0.024,0.026,0.031,0.013,0.089,0.020,0.159,0.650
3,Longwood,3928,0.375,0.145,0.149,0.034,0.013,0.004,0.009,0.006,...,0.012,0.005,0.002,0.010,0.011,0.007,0.043,0.015,0.061,0.882
4,Bay Village,935,0.495,0.031,0.030,0.049,0.105,0.041,0.078,0.073,...,0.070,0.049,0.060,0.041,0.040,0.026,0.108,0.002,0.241,0.308
5,Leather District,300,0.487,0.100,0.063,0.080,0.063,0.030,0.053,0.043,...,0.053,0.033,0.043,0.030,0.017,0.003,0.060,0.010,0.143,0.550
6,Chinatown,1548,0.488,0.091,0.059,0.076,0.068,0.032,0.056,0.048,...,0.054,0.036,0.046,0.033,0.021,0.006,0.068,0.008,0.158,0.519
7,North End,6188,0.509,0.003,0.054,0.153,0.093,0.051,0.029,0.045,...,0.064,0.057,0.027,0.040,0.036,0.017,0.104,0.011,0.202,0.426
8,Roxbury,10920,0.505,0.039,0.100,0.062,0.057,0.043,0.053,0.040,...,0.047,0.053,0.057,0.045,0.032,0.010,0.095,0.008,0.188,0.385
9,South End,15021,0.500,0.009,0.026,0.077,0.081,0.071,0.085,0.059,...,0.078,0.075,0.050,0.048,0.029,0.012,0.092,0.003,0.207,0.266
10,Back Bay,16006,0.482,0.030,0.048,0.078,0.065,0.053,0.048,0.057,...,0.073,0.061,0.044,0.058,0.052,0.022,0.140,0.007,0.263,0.330
11,East Boston,20876,0.525,0.011,0.033,0.066,0.075,0.090,0.060,0.048,...,0.062,0.065,0.053,0.042,0.028,0.016,0.103,0.017,0.199,0.209
12,Charlestown,13120,0.462,0.001,0.012,0.058,0.072,0.078,0.053,0.046,...,0.083,0.082,0.068,0.068,0.042,0.021,0.142,0.011,0.233,0.142
13,West End,4811,0.489,0.009,0.044,0.090,0.059,0.075,0.057,0.043,...,0.087,0.061,0.055,0.056,0.045,0.026,0.138,0.011,0.258,0.283
14,Beacon Hill,7899,0.475,0.006,0.019,0.110,0.085,0.048,0.036,0.061,...,0.090,0.068,0.054,0.050,0.047,0.024,0.133,0.012,0.257,0.276
15,Downtown,9111,0.508,0.042,0.043,0.095,0.068,0.052,0.059,0.064,...,0.063,0.046,0.046,0.044,0.040,0.018,0.109,0.008,0.238,0.383
16,Fenway,20402,0.465,0.129,0.134,0.060,0.042,0.027,0.019,0.023,...,0.046,0.027,0.015,0.018,0.009,0.006,0.036,0.002,0.081,0.725
17,Brighton,35004,0.494,0.011,0.081,0.139,0.064,0.060,0.035,0.026,...,0.053,0.047,0.033,0.025,0.026,0.019,0.090,0.021,0.159,0.472
18,West Roxbury,24399,0.462,0.003,0.014,0.031,0.039,0.058,0.069,0.071,...,0.042,0.056,0.075,0.089,0.061,0.039,0.221,0.031,0.390,0.102
19,Hyde Park,12926,0.490,0.015,0.019,0.040,0.025,0.066,0.060,0.087,...,0.036,0.068,0.089,0.071,0.057,0.029,0.175,0.018,0.349,0.145
20,Mattapan,2727,0.501,0.001,0.027,0.019,0.026,0.127,0.039,0.058,...,0.043,0.111,0.060,0.043,0.056,0.029,0.143,0.015,0.287,0.098
21,Dorchester,34123,0.508,0.010,0.033,0.076,0.059,0.074,0.060,0.062,...,0.073,0.063,0.047,0.053,0.045,0.020,0.128,0.010,0.249,0.231
22,South Boston Waterfront,4885,0.551,0.001,0.038,0.128,0.097,0.104,0.069,0.047,...,0.076,0.067,0.052,0.050,0.027,0.009,0.091,0.006,0.166,0.308
23,South Boston,28452,0.503,0.002,0.030,0.125,0.090,0.072,0.051,0.048,...,0.073,0.058,0.042,0.046,0.027,0.015,0.099,0.011,0.179,0.341
24,Allston,15645,0.510,0.056,0.118,0.146,0.069,0.048,0.021,0.020,...,0.047,0.019,0.022,0.021,0.015,0.009,0.050,0.005,0.090,0.651
25,Harbor Islands,44,0.705,0.000,0.000,0.068,0.068,0.182,0.091,0.250,...,0.000,0.227,0.000,0.000,0.000,0.000,0.000,0.000,0.273,0.136

In [131]:
neigh_age_15_19.to_csv('Boston_Neighborhood_Estimated_Age_Distribution_ACS_2015-2019.csv')